server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.171.109:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 521314
    #    type: com.alibaba.druid.pool.DruidDataSource
    #    druid:
    #      initialSize: 5
    #      minIdle: 5
    #      maxActive: 20
    #      maxWait: 10000
    #      timeBetweenEvictionRunMillis: 60000
    #      minEvictableIdleTimeMillis: 50000
    #      validationQuery: SELECT 'x'
    #      testWhileIdle: true
    #      testOnBorrow: false
    #      testOnReturn: false
    #      poolPreparedStatements: true
    #      maxPoolPreparedStatementPerConnectionSize: 10
    #      filters: stat
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #连接池名
      pool-name: hikari
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大存活时间（默认60000）
      idle-timeout: 180000
      #最大连接数（默认10）
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久，默认1800000
      max-lifetime: 1800000
      #连接超时时间（默认30000）
      connection-timeout: 30000
      #测试连接是否可用的语句
      connection-test-query: SELECT 1
#Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型别名（默认是类名）
  type-aliases-package: com.xdd.server.entity
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: true
#Mybatis SQL打印（方法所在包位置，不是mapper）
logging:
  level:
    com.xdd.server.mapper: debug

jwt:
  #JWT存储的请求头
  tokenHeader: Authorization
  #JWT加密的秘密钥
  secret: mySecret
  #JWT超时时间  24*60*60*1000
  expiration: 3600000
  #JWT负载的开头
  tokenHead: Bearer